<?php
	$title = 'Album::Eliminar';
	$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<p>Está seguro de eliminar el Album 
    <strong>'<?php echo $this->escapeHtml($album->title); ?>'</strong> por
    <strong>'<?php echo $this->escapeHtml($album->artist); ?>'</strong>?
</p>
<?php
$url = $this->url('album', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
    <input type="submit" name="del" value="Si" />
    <input type="submit" name="del" value="No" />
</div>
</form>

<a href="<?= $this->url('album', array('action' =>'index'))?>">Regresar</a>