<?php
	$title = 'Mis Albums';
	$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>"><img src="/img/add.png" title="Agregar Album"/> Nuevo Album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>"><img src="/img/edit.png" title="Editar Album"/></a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>"><img src="/img/delete.png" title="Eliminar Album"/></a>
    </td>
</tr>
<?php endforeach; ?>
</table>